name: tdmpc
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip
  - numpy
  - scipy
  - pillow
  - matplotlib
  - tqdm

  - pip:
      - torch==2.3.0
      - torchvision==0.18.0
      - torchaudio==2.3.0
      - "gymnasium[mujoco]"
      - mujoco
      - pyyaml
      - absl-py
      - imageio
      - imageio-ffmpeg
      - wandb
