task: HalfCheetah-v4
modality: state

exp_name: mujoco_halfcheetah_v4
seed: 1      

episode_length: 1000
action_repeat: 1

train_steps: 1000000
seed_steps: 10000

eval_freq: 20000
eval_episodes: 10